- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Ensure /usr/local/bin is in PATH for future sessions
  lineinfile:
    path: /root/.bashrc
    line: 'export PATH=$PATH:/usr/local/bin'
    state: present

- name: Run Helm install script
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
