- name: Set Kubernetes yum repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/repodata/repomd.xml.key

- name: Set CRI-O yum repo
  copy:
    dest: /etc/yum.repos.d/cri-o.repo
    content: |
      [cri-o]
      name=CRI-O
      baseurl=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/rpm/repodata/repomd.xml.key

- name: Disable swap
  command: swapoff -a

- name: Remove swap entry from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    replace: '# \g<0>'

- name: Set SELinux in permissive mode temporarily
  command: setenforce 0
  when: ansible_selinux.status == "enabled"

- name: Set SELinux in permissive mode permanently
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Load overlay module
  modprobe:
    name: overlay
    state: present

- name: Persist required kernel modules for Kubernetes
  copy:
    dest: /etc/modules-load.d/k8s-modules.conf
    content: |
      br_netfilter
      overlay
    owner: root
    group: root
    mode: '0644'

- name: Set sysctl params for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s-mod.conf
    content: |
      net.bridge.bridge-nf-call-iptables=1
      net.ipv4.ip_forward=1
      net.bridge.bridge-nf-call-ip6tables=1
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl params quietly
  command: sysctl --system -q

- name: Install cri-o and Kubernetes packages
  dnf:
    name:
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: true
    state: started

- name: Enable and start crio
  systemd:
    name: crio
    enabled: true
    state: started




